"""Trains the SentinelBox health MLP, compares it with the current rule-based score and
exports the weights for the ESP32 (firmware/SentinelBoxANN/sentinel_model.h).

Usage: python build_dataset.py && python train.py
"""

import json
import subprocess
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neural_network import MLPClassifier

from features import CLASS_HEALTH, CLASSES, FEATURES, LOG2_CLAMP, TEMP_SCALE, WINDOW, model_inputs, vibration_stats

ROOT = Path(__file__).parent
DATA = ROOT / "data/processed"
FIRMWARE = ROOT.parent / "firmware/SentinelBoxANN"
ARTIFACTS = ROOT / "artifacts"
REAL = ROOT / "data/real"  # prototype recordings from collect_serial.py
REAL_WEIGHT = 5  # each real window counts as this many synthetic ones
REAL_TEST_FRACTION = 0.25  # of the sessions, held out whole
HIDDEN = (16, 8)
SOFTMAX_T = 3.0  # softens probabilities for health_pct only; the class (argmax) is unchanged


def logits(model: MLPClassifier, X: np.ndarray) -> np.ndarray:
    h = X
    for i, (w, b) in enumerate(zip(model.coefs_, model.intercepts_)):
        h = h @ w + b
        if i < len(model.coefs_) - 1:
            h = np.maximum(h, 0)
    return h


def health(model: MLPClassifier, X: np.ndarray) -> np.ndarray:
    z = logits(model, X) / SOFTMAX_T
    p = np.exp(z - z.max(axis=1, keepdims=True))
    return (p / p.sum(axis=1, keepdims=True)) @ CLASS_HEALTH


def rule_based(X: np.ndarray, base_temp=24.5) -> np.ndarray:
    """The pre-ANN logic (src/lib/sentinel/mock.ts): weighted deviation score.
    Returns 0 (normal) / 2 (maintenance); the rule has no warning level."""
    dev = {
        "vib": np.abs(2 ** X[:, 0] - 1) * 100,
        "cur": np.abs(2 ** X[:, 3] - 1) * 100,
        "temp": np.abs(X[:, 4] * TEMP_SCALE) / base_temp * 100,
    }
    tol = {"temp": 20, "cur": 15, "vib": 30}
    s = {k: np.minimum(100, dev[k] / tol[k] * 100) for k in dev}
    hp = 100 - (0.40 * s["cur"] + 0.35 * s["temp"] + 0.25 * s["vib"])
    alarm = (hp < 70) | (np.maximum.reduce(list(s.values())) > 80)
    return np.where(alarm, 2, 0)


def kpis(y_true, y_pred) -> dict:
    fault, alarm = y_true > 0, y_pred > 0
    tp, fn = (fault & alarm).sum(), (fault & ~alarm).sum()
    fp, tn = (~fault & alarm).sum(), (~fault & ~alarm).sum()
    rate = lambda a, b: round(float(a / (a + b)), 4) if a + b else None  # noqa: E731
    return {
        "detection_rate": rate(tp, fn),
        "false_alarm_rate": rate(fp, tn),
        "missed_anomaly_rate": rate(fn, tp),
    }


def c_array(name, a):
    vals = ", ".join(f"{v:.8e}f" for v in np.asarray(a, dtype=np.float32).ravel())
    return f"static const float {name}[{a.size}] = {{{vals}}};\n"


def export_header(model: MLPClassifier, path: Path):
    W, B = model.coefs_, model.intercepts_
    n_params = sum(w.size + b.size for w, b in zip(W, B))
    h = [
        "// Generated by ml/train.py — do not edit.\n",
        f"// MLP {len(FEATURES)}-{'-'.join(map(str, HIDDEN))}-{len(CLASSES)}, {n_params} float32 params "
        f"({n_params * 4} bytes).\n",
        f"// Inputs: {', '.join(FEATURES)} (relative to the unit's baseline).\n",
        f"// Outputs: {', '.join(CLASSES)}.\n",
        "#pragma once\n\n",
        f"#define SENTINEL_N_IN {len(FEATURES)}\n",
        f"#define SENTINEL_H1 {HIDDEN[0]}\n",
        f"#define SENTINEL_H2 {HIDDEN[1]}\n",
        f"#define SENTINEL_N_OUT {len(CLASSES)}\n",
        f"#define SENTINEL_WINDOW {WINDOW}\n",
        f"#define SENTINEL_LOG2_MIN {LOG2_CLAMP[0]:.1f}f\n",
        f"#define SENTINEL_LOG2_MAX {LOG2_CLAMP[1]:.1f}f\n",
        f"#define SENTINEL_TEMP_SCALE {TEMP_SCALE:.1f}f\n",
        f"#define SENTINEL_SOFTMAX_T {SOFTMAX_T:.1f}f\n\n",
        c_array("SENTINEL_CLASS_HEALTH", CLASS_HEALTH),
    ]
    for i, (w, b) in enumerate(zip(W, B), 1):
        h += [c_array(f"SENTINEL_W{i}", w), c_array(f"SENTINEL_B{i}", b)]
    path.write_text("".join(h))
    return n_params


C_HARNESS = r"""
#include <stdio.h>
#include "sentinel_ann.h"
int main(void) {
  char mode;
  while (scanf(" %c", &mode) == 1) {
    if (mode == 'n') {  // network: 5 inputs -> probs + health
      float in[SENTINEL_N_IN], p[SENTINEL_N_OUT];
      for (int i = 0; i < SENTINEL_N_IN; i++)
        if (scanf("%f", &in[i]) != 1) return 1;
      sentinel_forward(in, p, 1.0f);
      printf("%.7f %.7f %.7f %.5f\n", p[0], p[1], p[2], sentinel_health_of(in));
    } else {  // vibration window -> stats
      static float acc[SENTINEL_WINDOW][3];
      for (int i = 0; i < SENTINEL_WINDOW; i++)
        if (scanf("%f %f %f", &acc[i][0], &acc[i][1], &acc[i][2]) != 3) return 1;
      sentinel_obs_t o;
      sentinel_vibration_stats(acc, SENTINEL_WINDOW, &o);
      printf("%.7g %.7g %.7g\n", o.vib_rms, o.vib_crest, o.vib_kurt);
    }
  }
  return 0;
}
"""


def check_c_parity(model, X, windows) -> dict:
    """Compiles sentinel_ann.h with gcc and compares it with the Python model."""
    with tempfile.TemporaryDirectory() as tmp:
        src, exe = Path(tmp) / "harness.c", Path(tmp) / "harness"
        src.write_text(C_HARNESS)
        subprocess.run(["gcc", "-O2", "-std=c99", f"-I{FIRMWARE}", str(src), "-o", str(exe), "-lm"], check=True)
        lines = [("n " + " ".join(f"{v:.8f}" for v in x)) for x in X]
        lines += [("v " + " ".join(f"{v:.6f}" for v in w.ravel())) for w in windows]
        out = subprocess.run([str(exe)], input="\n".join(lines), capture_output=True, text=True, check=True)
    rows = [list(map(float, line.split())) for line in out.stdout.strip().splitlines()]
    c_net, c_vib = np.array(rows[: len(X)]), np.array(rows[len(X) :])
    py_prob = model.predict_proba(X)
    py_vib = np.array([vibration_stats(w) for w in windows])
    return {
        "max_prob_diff": float(np.abs(c_net[:, :3] - py_prob).max()),
        "max_health_diff": float(np.abs(c_net[:, 3] - health(model, X)).max()),
        "same_class": float((c_net[:, :3].argmax(1) == py_prob.argmax(1)).mean()),
        "max_vib_stat_rel_diff": float((np.abs(c_vib - py_vib) / np.abs(py_vib)).max()),
    }


def load_real():
    """Prototype windows -> (X, y, session). Sensors that were simulated (not wired)
    are set to their baseline, like the firmware does."""
    files = sorted(REAL.glob("*.csv"))
    if not files:
        return None
    d = pd.concat([pd.read_csv(f) for f in files], ignore_index=True)
    d = d[d.vib_ok == 1]
    d.loc[d.cur_real == 0, "current"] = d.base_current
    d.loc[(d.temp_real == 0) | d.temp.isna(), "temp"] = d.base_temp
    base = {k: d["base_" + k].to_numpy() for k in FEATURES}
    X = model_inputs(d.vib_rms.to_numpy(), d.vib_crest.to_numpy(), d.vib_kurt.to_numpy(),
                     d.current.to_numpy(), d.temp.to_numpy(), base).astype(np.float32)
    return X, d.label.to_numpy(), (d.unit_id + "/" + d.session.astype(str)).to_numpy(), d.scenario.to_numpy()


def split_real(real, rng):
    """Holds out whole sessions, per label, so every class is tested when possible."""
    X, y, session, scenario = real
    held = []
    for label in np.unique(y):
        sessions = np.unique(session[y == label])
        if len(sessions) > 1:
            n = max(1, round(len(sessions) * REAL_TEST_FRACTION))
            held += list(rng.choice(sessions, n, replace=False))
    test = np.isin(session, held)
    return (X[~test], y[~test]), (X[test], y[test], scenario[test])


def main():
    tr, te = np.load(DATA / "train.npz"), np.load(DATA / "test.npz")
    X_train, y_train = tr["X"], tr["y"]
    real = load_real()
    if real is not None:
        (Xr, yr), real_test = split_real(real, np.random.default_rng(0))
        X_train = np.concatenate([X_train, np.repeat(Xr, REAL_WEIGHT, axis=0)])
        y_train = np.concatenate([y_train, np.repeat(yr, REAL_WEIGHT)])
        print(f"Real prototype data: {len(real[1])} windows, {len(np.unique(real[2]))} sessions "
              f"({len(yr)} train, {len(real_test[1])} held-out test)")
    model = MLPClassifier(
        hidden_layer_sizes=HIDDEN, activation="relu", alpha=1e-3, learning_rate_init=3e-3,
        max_iter=500, early_stopping=True, n_iter_no_change=25, random_state=0,
    )
    model.fit(X_train, y_train)
    y, pred = te["y"], model.predict(te["X"])

    print("=== Test set (fan speeds never seen in training) ===")
    print(classification_report(y, pred, target_names=CLASSES, digits=3))
    print("Confusion (rows = truth):\n", confusion_matrix(y, pred))

    per_scenario = pd.Series(pred == y).groupby(te["scenario"]).mean().round(3)
    print("\nAccuracy per scenario:\n" + per_scenario.to_string())

    ann, rule = kpis(y, pred), kpis(y, rule_based(te["X"]))
    print("\nKPI          ANN      rule (current firmware)")
    for k in ann:
        print(f"{k:22s} {ann[k]}    {rule[k]}")

    real_metrics = None
    if real is not None and len(real_test[1]):
        Xt, yt, sc = real_test
        pt = model.predict(Xt)
        print("\n=== Real prototype, held-out sessions ===")
        print(classification_report(yt, pt, labels=range(len(CLASSES)), target_names=CLASSES, digits=3,
                                    zero_division=0))
        print("Accuracy per scenario:\n" + pd.Series(pt == yt).groupby(sc).mean().round(3).to_string())
        real_metrics = {"windows": int(len(yt)), "accuracy": round(float((pt == yt).mean()), 4), "kpi": kpis(yt, pt)}
        print("KPI:", real_metrics["kpi"])

    FIRMWARE.mkdir(parents=True, exist_ok=True)
    n_params = export_header(model, FIRMWARE / "sentinel_model.h")

    raw = pd.read_csv(ROOT / "data/raw/uci_fan_accelerometer.csv")[["x", "y", "z"]].to_numpy()
    windows = [raw[i : i + WINDOW] for i in range(0, 50 * WINDOW, 5 * WINDOW)] + [
        raw[i : i + WINDOW] for i in range(100000, 150000, 5000)
    ]
    parity = check_c_parity(model, te["X"][:2000], windows)
    print(f"\nExported {n_params} params ({n_params * 4} B) -> {FIRMWARE / 'sentinel_model.h'}")
    print("C vs Python:", parity)

    ARTIFACTS.mkdir(exist_ok=True)
    (ARTIFACTS / "metrics.json").write_text(json.dumps({
        "architecture": [len(FEATURES), *HIDDEN, len(CLASSES)],
        "params": n_params,
        "test_accuracy": round(float((pred == y).mean()), 4),
        "confusion": confusion_matrix(y, pred).tolist(),
        "per_scenario_accuracy": per_scenario.to_dict(),
        "kpi_ann": ann,
        "kpi_rule": rule,
        "c_parity": parity,
        "real_prototype": real_metrics,
    }, indent=2, default=float))


if __name__ == "__main__":
    main()
