// SentinelBox health network: feature extraction + MLP inference in plain C.
// No Arduino dependencies, so ml/train.py can compile it with gcc and check that it
// matches the Python model. Mirrors ml/features.py; weights live in sentinel_model.h
// (generated by ml/train.py, do not edit by hand).
#pragma once

#include <math.h>
#include "sentinel_model.h"

typedef struct {
  float vib_rms;    // g, RMS of the accel magnitude after removing each axis' mean
  float vib_crest;  // peak / RMS
  float vib_kurt;   // Pearson kurtosis of the zero-mean samples
  float current;    // A, mean over the window
  float temp;       // °C
} sentinel_obs_t;

typedef struct {
  float prob[SENTINEL_N_OUT];  // NORMAL, WARNING, MAINTENANCE (softened by SENTINEL_SOFTMAX_T)
  int cls;
  float health_pct;  // 0-100, 100 = the learned baseline
  // Health lost when only that sensor deviates from its baseline (0 = no impact).
  float vibration_score;
  float current_score;
  float temp_score;
} sentinel_result_t;

// acc: n samples of {x, y, z} in g.
static inline void sentinel_vibration_stats(const float (*acc)[3], int n, sentinel_obs_t *out) {
  float mean[3] = {0, 0, 0};
  for (int i = 0; i < n; i++)
    for (int a = 0; a < 3; a++) mean[a] += acc[i][a];
  for (int a = 0; a < 3; a++) mean[a] /= n;

  float sum_m2 = 0, peak = 0, sum2 = 0, sum4 = 0;
  for (int i = 0; i < n; i++) {
    float m2 = 0;
    for (int a = 0; a < 3; a++) {
      float d = acc[i][a] - mean[a];
      float d2 = d * d;
      m2 += d2;
      sum2 += d2;
      sum4 += d2 * d2;
    }
    sum_m2 += m2;
    float m = sqrtf(m2);
    if (m > peak) peak = m;
  }
  float rms = sqrtf(sum_m2 / n) + 1e-9f;
  float var = sum2 / (3.0f * n) + 1e-12f;
  out->vib_rms = rms;
  out->vib_crest = peak / rms;
  out->vib_kurt = (sum4 / (3.0f * n)) / (var * var);
}

static inline float sentinel_log2_ratio(float x, float base) {
  float r = log2f(fmaxf(x, 1e-6f) / base);
  return fminf(fmaxf(r, SENTINEL_LOG2_MIN), SENTINEL_LOG2_MAX);
}

static inline void sentinel_inputs(const sentinel_obs_t *x, const sentinel_obs_t *base, float in[SENTINEL_N_IN]) {
  in[0] = sentinel_log2_ratio(x->vib_rms, base->vib_rms);
  in[1] = sentinel_log2_ratio(x->vib_crest, base->vib_crest);
  in[2] = sentinel_log2_ratio(x->vib_kurt, base->vib_kurt);
  in[3] = sentinel_log2_ratio(x->current, base->current);
  in[4] = (x->temp - base->temp) / SENTINEL_TEMP_SCALE;
}

static inline void sentinel_dense(const float *in, int n_in, const float *w, const float *b, int n_out, float *out,
                                  int relu) {
  for (int j = 0; j < n_out; j++) {
    float s = b[j];
    for (int i = 0; i < n_in; i++) s += in[i] * w[i * n_out + j];
    out[j] = (relu && s < 0) ? 0 : s;
  }
}

// temperature > 1 softens the probabilities (same argmax) so health_pct changes gradually.
static inline void sentinel_forward(const float in[SENTINEL_N_IN], float prob[SENTINEL_N_OUT], float temperature) {
  float h1[SENTINEL_H1], h2[SENTINEL_H2];
  sentinel_dense(in, SENTINEL_N_IN, SENTINEL_W1, SENTINEL_B1, SENTINEL_H1, h1, 1);
  sentinel_dense(h1, SENTINEL_H1, SENTINEL_W2, SENTINEL_B2, SENTINEL_H2, h2, 1);
  sentinel_dense(h2, SENTINEL_H2, SENTINEL_W3, SENTINEL_B3, SENTINEL_N_OUT, prob, 0);
  float mx = prob[0];
  for (int k = 1; k < SENTINEL_N_OUT; k++) mx = fmaxf(mx, prob[k]);
  float z = 0;
  for (int k = 0; k < SENTINEL_N_OUT; k++) z += (prob[k] = expf((prob[k] - mx) / temperature));
  for (int k = 0; k < SENTINEL_N_OUT; k++) prob[k] /= z;
}

static inline float sentinel_health_of(const float in[SENTINEL_N_IN]) {
  float p[SENTINEL_N_OUT];
  sentinel_forward(in, p, SENTINEL_SOFTMAX_T);
  float h = 0;
  for (int k = 0; k < SENTINEL_N_OUT; k++) h += p[k] * SENTINEL_CLASS_HEALTH[k];
  return h;
}

// Runs the network on the full reading, then once per sensor with the other sensors
// held at baseline, so the technician sees which signal caused the alert.
static inline void sentinel_evaluate(const sentinel_obs_t *x, const sentinel_obs_t *base, sentinel_result_t *r) {
  float in[SENTINEL_N_IN];
  sentinel_inputs(x, base, in);
  sentinel_forward(in, r->prob, SENTINEL_SOFTMAX_T);
  r->cls = 0;
  for (int k = 1; k < SENTINEL_N_OUT; k++)
    if (r->prob[k] > r->prob[r->cls]) r->cls = k;

  // Rescale so that the unit's own baseline reads exactly 100 %.
  float zero[SENTINEL_N_IN] = {0};
  float healthy = sentinel_health_of(zero), floor_h = SENTINEL_CLASS_HEALTH[SENTINEL_N_OUT - 1];
  float h = 0;
  for (int k = 0; k < SENTINEL_N_OUT; k++) h += r->prob[k] * SENTINEL_CLASS_HEALTH[k];
  r->health_pct = 100.0f * fminf(fmaxf((h - floor_h) / (healthy - floor_h), 0), 1);
  float only[SENTINEL_N_IN];
  float *scores[3] = {&r->vibration_score, &r->current_score, &r->temp_score};
  const int first[3] = {0, 3, 4}, last[3] = {2, 3, 4};  // input ranges per sensor
  for (int s = 0; s < 3; s++) {
    for (int i = 0; i < SENTINEL_N_IN; i++) only[i] = (i >= first[s] && i <= last[s]) ? in[i] : 0;
    float drop = (healthy - sentinel_health_of(only)) / (healthy - floor_h);
    *scores[s] = 100.0f * fminf(fmaxf(drop, 0), 1);
  }
}
